#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

// Helper function to escape strings for JavaScript
function escapeForJS(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');
}

// Read the static files
const indexHtml = readFileSync(join(projectRoot, 'static/index.html'), 'utf-8');
const appJs = readFileSync(join(projectRoot, 'static/assets/app.js'), 'utf-8');

// Generate the static-web.js file
const staticWebContent = `// Embedded static files for the web interface
// This file is auto-generated by scripts/build-static.js - do not edit manually!

export const STATIC_FILES = {
  '/': \`${escapeForJS(indexHtml)}\`,
  
  '/assets/app.js': \`${escapeForJS(appJs)}\`
};
`;

// Write the generated file
const outputPath = join(projectRoot, 'src/static-web.js');
writeFileSync(outputPath, staticWebContent, 'utf-8');

console.log('✅ Built static files successfully!');
console.log(`   - Generated: ${outputPath}`);
console.log(`   - HTML size: ${Math.round(indexHtml.length / 1024)}KB`);
console.log(`   - JS size: ${Math.round(appJs.length / 1024)}KB`); 